name: musicafemina
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
 sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_map_tappable_polyline: ^5.0.0
  enum_to_string: ^2.0.1

  latlong2: ^0.9.0

  location: ^4.2.0 # error wenn auf neuesten version. 4.2.0 funktioniert
  analyzer_plugin: ^0.11.2
  audioplayers: ^5.0.0
  just_audio: ^0.9.34
  google_fonts: ^5.1.0
  flutter_map: ^5.0.0
  http: ^1.0.0
  youtube_player_flutter: ^8.1.2
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/images/waypoints_all/

  # clara
  - assets/images/clara_img/
  - assets/images/clara_img/clara_argentinierstrasse/
  - assets/images/clara_img/clara_bauernmarkt/
  - assets/images/clara_img/clara_graben/
  - assets/images/clara_img/clara_heldenplatz/
  - assets/images/clara_img/clara_musikvereinplatz/
  - assets/images/clara_img/clara_tuchlauben/

  - assets/audio/clara_audio/

  # baker
  - assets/images/baker_img/
  - assets/images/baker_img/baker_favoritenstrasse/
  - assets/images/baker_img/baker_kaerntner/
  - assets/images/baker_img/baker_parlament/
  - assets/images/baker_img/baker_ring/
  - assets/images/baker_img/baker_seilerstaette/

  - assets/audio/baker_audio/

  # ns
  - assets/images/ns_img/
  - assets/images/ns_img/ns_alserstrasse/
  - assets/images/ns_img/ns_johannesgasse/
  - assets/images/ns_img/ns_kaasgraben/
  - assets/images/ns_img/ns_oppolzergasse/
  - assets/images/ns_img/ns_rahlgasse/
  - assets/images/ns_img/ns_rechtewienzeile/
  - assets/images/ns_img/ns_strozzigasse/
  - assets/images/ns_img/ns_wollzeile/

  - assets/audio/ns_audio/

  # wiener
  - assets/images/wiener_img/
  - assets/images/wiener_img/wiener_augustinerkirche/
  - assets/images/wiener_img/wiener_baeckerstrasse/
  - assets/images/wiener_img/wiener_florianigasse/
  - assets/images/wiener_img/wiener_helfersdorferstr/
  - assets/images/wiener_img/wiener_himmelpfortgasse/
  - assets/images/wiener_img/wiener_karlsplatz/
  - assets/images/wiener_img/wiener_kohlmarkt/
  - assets/images/wiener_img/wiener_marxerfriedhof/
  - assets/images/wiener_img/wiener_michaelerkirche/
  - assets/images/wiener_img/wiener_rabensteig/
  - assets/images/wiener_img/wiener_rasumovskygasse/
  - assets/images/wiener_img/wiener_ungargasse/

  - assets/audio/wiener_audio/

  # strauss
  - assets/images/strauss_img/
  - assets/images/strauss_img/strauss_karlsplatz/
  - assets/images/strauss_img/strauss_landstrasserhpt/
  - assets/images/strauss_img/strauss_nussdorf/
  - assets/images/strauss_img/strauss_palaiscoburg/
  - assets/images/strauss_img/strauss_prater/
  - assets/images/strauss_img/strauss_spiegelgasse/
  - assets/images/strauss_img/strauss_wiednerhauptstr/
  - assets/images/strauss_img/strauss_zieglergasse/

  - assets/audio/strauss_audio/
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
